name: dprint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Check formatting with dprint
        uses: dprint/check@v2.3
